eroice/urls.py
# Import necessary modules
from django.contrib import admin  # Import the admin module
from django.urls import path       # Import the path function for URL routing
from . import views

# Define the URL patterns for the project
urlpatterns = [
    path('admin', admin.site.urls),  # URL pattern for the admin site
    path('', views.landing_view, name='landing'),  # Landing page URL
    path('login', views.login_view, name='login'),  # Login page URL
    path('logout', views.logout_view, name='logout'),  # Logout URL
    path('signup', views.register_view, name='signup'),  # User registration URL
    path('write', views.write_view, name='write'),  # URL for writing a new story
    path('home', views.home_view, name='home'),  # Home page URL
    path('story/<str:pk_story>', views.story_view),  # Story page URL with story ID parameter
    path('genre/<str:pk_genre>', views.genre_view),  # URL for stories of a specific genre with genre ID parameter
]

# Assign the custom view for handling 404 errors
handler404 = views.handle_not_found
handler500 = views.handle_server_error

eroice/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import pre_save
import math

# User profile model
class Profile(models.Model):
    # One-to-One relationship with the User model
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name

# Genre model for categorizing stories
class Genre(models.Model):
    # Category name for stories
    name = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name

# Story model to store user-created stories
class Story(models.Model):
    # ForeignKey relationship with the Profile model for the author
    user = models.ForeignKey(Profile, null=True, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, null=True)
    content = models.TextField(null=True)
    genre = models.ManyToManyField(Genre, blank=False)  # A story can belong to multiple genres
    view = models.PositiveSmallIntegerField(default=0, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    @property
    def word_count(self):
        return len(self.content.split()) if self.content else 0  # Calculate the word count of the story content

    def __str__(self):
        return self.title or ''

    def genres(self):
        return self.genre.all()

    # Estimate reading time (250 words / 1 minute)
    def reading_time(self):
        return f"{math.ceil(self.word_count / 250)} min"

# Like model to represent user likes on stories
class Like(models.Model):
    # ForeignKey relationship with the Profile model for the user and the Story model for the story
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    story = models.ForeignKey(Story, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

# Comment model for user comments on stories
class Comment(models.Model):
    # ForeignKey relationship with the Profile model for the user and the Story model for the story
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    story = models.ForeignKey(Story, on_delete=models.CASCADE)
    comment = models.TextField(null=True)
    created = models.DateTimeField(auto_now_add=True)

eroice/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Story, Comment

# Common base form for user registration
class BaseUserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

# Form for creating a new user with user registration
class CreateUserForm(BaseUserRegistrationForm):
    pass

# Form for creating a new user during landing page registration
class CreateUserFormLanding(BaseUserRegistrationForm):
    pass

# Form for writing a new story
class WriteForm(ModelForm):
    class Meta:
        model = Story
        exclude = ["user", "likes"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Customize widget attributes for better user interaction
        for field_name in self.fields:
            self.fields[field_name].widget.attrs.update({'class': 'form-control'})
        # Set minimum length for content field
        self.fields['content'].widget.attrs['minlength'] = '200'

# Form for adding a new comment to a story
class CommentForm(ModelForm):
    class Meta:
        model = Comment
        exclude = ["user", "story"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Customize widget attribute for the comment field
        self.fields['comment'].widget.attrs.update({'name': 'comment'})

eroice/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from .forms import CreateUserForm, CreateUserFormLanding, WriteForm, CommentForm
from .models import Story, Genre, Profile, Like, Comment
from django.core.mail import send_mail

# Helper function for user registration and landing views
def registration_logic(request, form_class, template_name):
    if request.user.is_authenticated:
        return redirect("home")

    form = form_class(request.POST or None)
    if request.method == "POST" and form.is_valid():
        form.save()
        user = form.cleaned_data.get("username")
        email = form.cleaned_data.get("email")
        messages.success(
            request,
            f"Hi, {user}! Your Eroice account is successfully created! Please Log in.",
        )
        send_mail(
            f"Welcome to Eroice, {user}",
            f"Dear {user},\n\nThank you for choosing Eroice. We're delighted to welcome you to our community!\n\nBelow are your account details:\n\nUsername: {user}\nEmail: {email}\n\nFeel free to explore our platform, share your stories, and engage with fellow writers and readers.\n\nIf you have any questions or need assistance, please don't hesitate to contact us.\n\nBest regards,\nThe Eroice Team",
            "eroice.id@gmail.com",
            [email],
            fail_silently=False,
        )
        return redirect("login")

    context = {"form": form}
    return render(request, template_name, context)

# Login page view
def login_view(request):
    if request.user.is_authenticated:
        return redirect("home")

    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect("home")
        else:
            messages.info(request, "Username or password incorrect")

    return render(request, "login/index.html", {})

# Logout user view
def logout_view(request):
    logout(request)
    return redirect("landing")

# User registration view
def register_view(request):
    return registration_logic(request, CreateUserForm, "signup/index.html")

# Landing page view
def landing_view(request):
    return registration_logic(request, CreateUserFormLanding, "landing/index.html")


# Home page view


@login_required(login_url="login")
def home_view(request):
    username = request.user.username
    stories = Story.objects.all()
    genres = Genre.objects.all()

    return render(
        request,
        "home/index.html",
        {"username": username, "stories": stories, "genres": genres},
    )


# Write view


@login_required(login_url="login")
def write_view(request):
    username = request.user.username
    if request.method == "POST":
        form = WriteForm(request.POST)
        if form.is_valid():
            stock = form.save(commit=False)
            stock.user = Profile.objects.get(user=request.user)
            stock.save()
            form.save_m2m()
            return redirect("/")
    else:
        form = WriteForm()

    genres = Genre.objects.all()
    context = {"form": form, "genres": genres, "username": username}
    return render(request, "write/index.html", context)


@login_required(login_url="login")
def story_view(request, pk_story):
    username = request.user.username
    story = get_object_or_404(Story, id=pk_story)
    user_profile = Profile.objects.get(user=request.user)
    liked_by_user = story.like_set.filter(user=user_profile).exists()
    
    if request.method == "POST":
        if request.POST.get("comment"):
            form = CommentForm(request.POST)
            if form.is_valid():
                stock = form.save(commit=False)
                stock.user = user_profile
                stock.story = story
                stock.save()
        else:
            if liked_by_user:
                story.like_set.filter(user=user_profile).delete()
            else:
                Like.objects.create(user=user_profile, story=story)

    else:
        form = CommentForm()
        story.view += 1
        story.save()

    likes = story.like_set.all().count()
    genres = Genre.objects.all()

    like_icon = (
        "bxs-heart text-red-500 dark:text-red-500"
        if liked_by_user
        else "bx-heart text-primary dark:text-gray-50"
    )
    
    comments = Comment.objects.filter(story=story)

    context = {
        "story": story,
        "genres": genres,
        "likes": likes,
        "like_icon": like_icon,
        "form": form,
        "comments": comments,
        "username": username,
    }
    
    return render(request, "story/index.html", context)


# 404 error view


def handle_not_found(request, exception):
    return render(request, "404/index.html", {})


# 500 error view


def handle_server_error(request):
    return render(request, "500/index.html", {})


# Genre view


@login_required(login_url="login")
def genre_view(request, pk_genre):
    username = request.user.username
    stories = Story.objects.filter(genre__name=pk_genre)
    genres = Genre.objects.all()

    context = {
        "genre": pk_genre,
        "stories": stories,
        "genres": genres,
        "username": username,
    }
    return render(request, "genre/index.html", context)

eroice/templates/story/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{ story.title }} | Eroice</title>
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    <script src="https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js" defer></script>
    <link rel="stylesheet" href="https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css" />
</head>

<body x-data="global()" x-init="themeInit()" :class="isMobileMenuOpen ? 'max-h-screen overflow-hidden relative' : ''"
    class="dark:bg-slate-950">
    </div>
    <div id="main">
        {% include 'navbar.html' %}
        <div>
            <div class="container mx-auto">
                <div class="py-16 lg:py-20">
                    <div class="flex flex-col pb-6">
                        <h3 class="font-body text-4xl font-semibold text-primary dark:text-gray-50">
                            {{ story.title }}
                        </h3>
                    </div>
                    <div class="pt-8">
                        <div class="pb-8">
                            <div class="flex items-center pb-4">
                                <div class="flex">
                                    <i
                                        class="bx mr-2 cursor-pointer text-3xl text-primary dark:text-gray-50 bxs-user-circle"></i>
                                    <h3 class="font-body text-xl text-primary dark:text-gray-50">
                                        {{ story.user }}
                                    </h3>
                                </div>
                            </div>
                            <span class="flex py-2">
                                <form id="like" action="" method="POST" class="mr-2 pt-[0.15rem]">
                                    {% csrf_token %}
                                    <button id="like-button" type="submit">
                                        <i class="bx {{ like_icon }} text-2xl"></i>
                                    </button>
                                </form>
                                <h5 id="like-number"
                                    class="font-body font-light text-lg text-primary dark:text-gray-50">
                                    {{ likes }}
                                </h5>
                                <h5 id="like-number"
                                    class="ml-4 font-body font-light text-lg text-primary dark:text-gray-50">
                                    {{ story.view }} views
                                </h5>
                            </span>
                            {% for genre in story.genres %}
                            <a href="/genre/{{ genre }}">
                                <span
                                    class="my-4 inline-block rounded-full bg-sky-200 dark:bg-sky-500 px-3 mx-[0.1rem] py-1 font-body text-sm text-sky-800 dark:text-sky-50">
                                    {{ genre }}</span>
                            </a>
                            {% endfor %}
                        </div>
                        <div id="content">
                            {{ story.content|linebreaks }}
                        </div>
                    </div>
                </div>
            </div>
            <div class="container mx-auto">
                <form class="border border-gray-300 dark:border-gray-500 rounded-lg p-4 mb-6" method="POST" action="">
                    {% csrf_token %}
                    <textarea name="comment" cols="40" rows="5"
                        class="mb-4 form-control bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-sky-600 focus:border-sky-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-gray-50 dark:focus:ring-blue-500 dark:focus:border-blue-500"
                        required="" id="id_comment" placeholder="Discuss this story..."></textarea>
                    <button type="submit"
                        class="text-white bg-sky-600 hover:bg-sky-700 focus:ring-4 focus:outline-none focus:ring-sky-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-sky-600 dark:hover:bg-sky-700 dark:focus:ring-sky-800">
                        Post comment
                    </button>
                </form>
                {% for comment in comments %}
                <div class="border border-gray-300 dark:border-gray-500 rounded-lg p-4 mb-6">
                    <div class="flex justify-between">
                        <div class="flex">
                            <i
                                class="bx mr-2 cursor-pointer text-2xl text-primary dark:text-gray-50 bxs-user-circle pt-[0.15rem]"></i>
                            <h3 class="font-body text-lg text-primary dark:text-gray-50">
                                {{ comment.user }}
                            </h3>
                        </div>
                        <h6 class="text-sm font-light text-gray-900 dark:text-gray-50">{{ comment.created.date }}</h6>
                    </div>
                    <div class="mt-6 text-gray-900 dark:text-gray-50">
                        <p>{{ comment.comment|capfirst }}</p>
                    </div>
                </div>
                {% endfor %}
            </div>
            {% include 'footer.html' %}
        </div>
        <script src="https://cdn.jsdelivr.net/npm/gsap@3.12.2/dist/gsap.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.7.0.js"
            integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM=" crossorigin="anonymous"></script>
        <script>
            $(document).ready(function () {
                var $likeButton = $('#like-button');
                var $likeIcon = $likeButton.find('i');
                var $likeNumber = $('#like-number');
                var likeCount = parseInt($likeNumber.text());
                $likeNumber.text(likeCount + (likeCount === 1 ? ' like' : ' likes'));

                $likeButton.click(function () {
                    if (!$likeIcon.hasClass('bxs-heart')) {
                        $likeIcon.removeClass('bx-heart text-primary dark:text-gray-50').addClass('bxs-heart text-red-500 dark:text-red-500');
                        likeCount++;
                    } else {
                        $likeIcon.removeClass('bxs-heart text-red-500 dark:text-red-500').addClass('bx-heart text-primary dark:text-gray-50');
                        likeCount--;
                    }

                    $likeNumber.text(likeCount + (likeCount === 1 ? ' like' : ' likes'));

                    gsap.timeline({})
                        .to($likeButton, { duration: 0.4, scale: 1.3 })
                        .to($likeButton, { duration: 0.4, scale: 1 });
                });

                $('#like').submit(function (event) {
                    event.preventDefault();
                    $.post($(this).attr('action'), $(this).serialize());
                });
            });
        </script>
        <script src="{% static 'js/script.js' %}"></script>
        <script>
            const contentChildren = document.querySelectorAll("#content > *");

            contentChildren.forEach(child => {
                child.classList.add("text-primary", "dark:text-gray-50", "py-2", "text-justify");
            });
        </script>
</body>

</html>